### ISSUE TITLE
`echo 'test';` working on my site:  (maybe forgot to deploy newest ver on wordpress.org)

### ISSUE THREAD

**Issue by kwbtdisk** [stellarwp/kadence-blocks#3]
This line https://github.com/kadencethemes/kadence-blocks/blob/ae1e9b6647be007b7e50b32668df4162c136e46b/dist/class-kadence-blocks-frontend.php#L253
<img width="1247" alt="screenshot 2018-12-03 at 22 23 19" src="https://user-images.githubusercontent.com/2969635/49376281-19f61b80-f74a-11e8-825b-c59007dcb20a.png">

I really appreciate your works! Great Job 😄

**Comment by kadencethemes** [comment]
Thanks, I just updated with that removed.
