### ISSUE TITLE
Add yandex_zen ICON support

### ISSUE THREAD

**Issue by karpalig** [stellarwp/kadence-blocks#376]
https://github.com/stellarwp/kadence-blocks/blob/c4d1d8da59973664cd79734735eca71aee473c02/includes/icons-array.php#L1148C1-L1148C1

`$faico['fa_yandex_dzen'] = array('vB'=>'0 0 512 512', 'cD'=>array(array('nE'=>'path','aBs'=>array('d'=>'M461.512 246.482h.103a9.38 9.38 0 0 0 3.793-.792 9.376 9.376 0 0 0 5.556-9.449C461.54 132.584 379.472 50.488 275.806 41.045a9.388 9.388 0 0 0-10.241 9.462c1.633 137.759 19.806 194.051 195.947 195.975Zm0 19.036c-176.141 1.924-194.304 58.216-195.938 195.975a9.4 9.4 0 0 0 3.016 7.009 9.4 9.4 0 0 0 7.225 2.453c103.667-9.443 185.734-91.53 195.149-195.196a9.362 9.362 0 0 0-.463-3.87 9.365 9.365 0 0 0-1.996-3.348 9.902 9.902 0 0 0-6.993-3.023ZM235.565 41.092C132.227 50.807 50.423 132.885 41.045 236.26a9.38 9.38 0 0 0 5.56 9.437 9.377 9.377 0 0 0 3.79.794h.112c175.559-2.018 193.685-58.281 195.337-195.946a9.427 9.427 0 0 0-3.042-7.008 9.415 9.415 0 0 0-7.237-2.445ZM50.498 265.51c-2.92-.329-5.21 1.06-7.003 3.013a9.413 9.413 0 0 0-2.459 7.218c9.377 103.376 91.191 185.453 194.529 195.168a9.403 9.403 0 0 0 7.238-2.449 9.398 9.398 0 0 0 3.031-7.013c-1.652-137.655-19.768-193.919-195.336-195.937Z'))));`

**Comment by kadencewp** [comment]
This was added in a previous release
